MyBlog_test/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^blog/', include(('blog.urls', 'blog'), namespace='blog')),
]

blog/urls.py
# -*- coding:utf-8 -*-
"""
@author:SiriYang
@file:urls.py
@time:2018/9/14 19:07
"""
from django.urls import path, re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.index,name='index'),
    re_path(r'^article/(?P<article_id>[0-9]+)/$', views.article_page, name='article_page'),
    re_path(r'^edit/(?P<article_id>[0-9]+)/$', views.edit_page, name='edit_page'),
    re_path(r'^edit/action$', views.edit_action, name='edit_action'),
]

blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):

    title = models.CharField(max_length=32,default='Title')
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse

from . import models


# Create your views here.

def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {"articles": articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    article_id=request.POST.get('article_id','0')

    if article_id=='0':
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {"articles": articles})

    article = models.Article.objects.get(pk=article_id)
    article.title=title
    article.content=content
    article.save()
    return render(request, 'blog/article_page.html', {'article': article})

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章页面</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<h3>{{ article.content }}</h3>
<b/><b/>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
<b/>
<a href="{% url 'blog:index' %}">返回</a>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑界面</title>
     <link rel="stylesheet" type="text/css" href="edit_page.css" />
    <style>
        *{
    font-family: Arial;
    font-size: 40px;
}
        #header{
            width: 100%;
            height: 100px;


        }
        #branding{
            height:20px;
            width:auto;
            float: left;
            margin:20% 0;
        }
        #branding h1{
            margin: 0 0 8px;
        }
        #main_body{
            background-color: lavender;
        }
        #main_body form{
            width: 40%;
            height: 800px;
        }
        #main_body form input{
            text-align: center;
            margin:0 auto;
            color: tomato;
            background-color: seashell;
            position:relative;
        }

        #main_body form label{
            color: steelblue;
        }
        #main_body form button{
            height: 40px;
            width: 100px;
            text-align: center;
            float: right;
            margin: 0 auto;
        }
        #main_body form button a{
            font-size: 30px;
            color: coral;
            text-align: center;
            text-decoration: none;
            margin: auto;
            float:left;
        }
        #main_body form button a:hover{
            color: cornflowerblue;
        }
    </style>
</head>
<body>
<div id="header">
    <div id="branding">
        <h1 id="site_name">
            <a href="index.html" My Blog></a>
        </h1>
    </div>
</div>
<div id="main_body">
    <form action="{% url 'blog:edit_action' %}" method="post">
        {% csrf_token %}
            <input type="hidden" name="article_id" value="{{ article.id | default:'0'}}">
            <label>文章标题
                <input type="text" name="title" value="{{ article.title }}"/>
            </label>
            <br/>
            <label>文章内容
                <textarea name="content" cols="40" rows="10" >
                    {{ article.content }}
                </textarea>

            </label>
            <br/>
        <input type="submit" value="提交" style="border-bottom-color: tomato" />
    </form>
</div>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的博客</title>
     <style type=".../css/index.css" >
         *{font-size: 30px;}

     </style>
</head>
<body>
<div class="top_title">
    <button type="button" >
        <a href="{% url 'blog:edit_page' 0 %}">新文章</a>
    </button>
</div>
{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
    <br/>
{% endfor %}
</body>
</html>

blog/templates/blog/register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>此处有注册</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    
</body>
</html>